"""C9 — full validate() differential against golden from the current TS.

Golden (``fixtures/golden/validate/*.json``) is generated by running the current
TS ``validate()`` per phase on the (normalized) seeds with the current package
config — see ``tools/gen_golden.mjs``. crucible normalizes identically and must
produce the same structural / scoring / crossValidation / meta. The ``guidance``
layer is deferred (C7), so it is excluded from the comparison.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import pytest

from crucible import validate
from crucible.config import load_defaults, merge_config

ROOT = Path(__file__).resolve().parents[1]
CASES_DIR = ROOT / "fixtures" / "test-surface" / "cases"
GOLDEN_DIR = ROOT / "fixtures" / "golden" / "validate"

_DEFAULTS = load_defaults()
_NO_TYPES = merge_config(_DEFAULTS, {"structuralRequirements": {"enforceTypes": False}})

# (golden file stem) -> (seed, phase, activeEntityId, config)
CASES: dict[str, tuple[str, str, str | None, Any]] = {
    "planning-spec": ("seed-planning-spec", "planning_spec", None, _DEFAULTS),
    "epic-decomposition": ("seed-epic-decomposition", "epic_decomposition", None, _DEFAULTS),
    "epic-expansion": ("seed-epic-expansion", "epic_expansion", "ep-1", _DEFAULTS),
    "ticket-decomposition": ("seed-ticket-decomposition", "ticket_decomposition", "ep-1", _DEFAULTS),
    "ticket-expansion": ("seed-ticket-expansion", "ticket_expansion", "tkt-1-1", _DEFAULTS),
    "ticket-expansion-no-types": ("seed-ticket-expansion", "ticket_expansion", "tkt-1-1", _NO_TYPES),
    "cross-validation": ("seed-cross-validation", "cross_validation", None, _DEFAULTS),
    "cross-validation-warn": ("seed-cross-validation", "cross_validation", "ep-1", _DEFAULTS),
}

_VOLATILE = {"generatedAt", "validatorVersion"}


def _strip(node: Any) -> Any:
    if isinstance(node, list):
        return [_strip(n) for n in node]
    if isinstance(node, dict):
        return {k: _strip(v) for k, v in node.items() if k not in _VOLATILE}
    return node


def _load_normalized(name: str) -> dict[str, Any]:
    raw = json.loads((CASES_DIR / f"{name}.json").read_text(encoding="utf-8"))
    raw.pop("$testSurface", None)
    raw["epics"] = raw.get("epics") or []
    raw["blueprints"] = raw.get("blueprints") or []
    for epic in raw["epics"]:
        epic["tickets"] = epic.get("tickets") or []
        for ticket in epic["tickets"]:
            if ticket.get("dependencies") is None:
                ticket["dependencies"] = []
    return raw


@pytest.mark.parametrize("case", list(CASES.keys()))
def test_validate_matches_golden(case: str) -> None:
    seed_name, phase, aid, config = CASES[case]
    seed = _load_normalized(seed_name)
    ctx: dict[str, Any] = {"phase": phase, "config": config}
    if aid is not None:
        ctx["activeEntityId"] = aid

    actual = _strip(validate(seed, ctx).to_json_dict())  # type: ignore[union-attr]
    golden = _strip(json.loads((GOLDEN_DIR / f"{case}.json").read_text(encoding="utf-8")))

    # Guidance layer is deferred (C7) — compare everything else.
    actual.pop("guidance", None)
    golden.pop("guidance", None)

    assert actual == golden
